name: heroku deploy

on:
  push:
    branches:
      - dev

jobs:

  deploy:

    needs: testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'django-libraryapp'
          heroku_email: ${{secrets.EMAIL_DEPLOY}}
      - name: Success message
        run: echo Successfully Deploy.!
