name: heroku deploy

on:
    push:
        branches:
            - dev
            - master

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: set up python 3.7
              uses: actions/setup-python@v1
              with:
                python-version: 3.7
            - name: Lint with flake8
              run: |
                python -m pip install --upgrade pip
                pip install flake8 black
                # -----------------------
                # stop the build if there are Python syntax errors or undefined names
                # -----------------------
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # -----------------------
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                # -----------------------
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
                # -----------------------
                # checks with black
                # -----------------------  
                black .
            - uses: akhileshns/heroku-deploy@v3.4.6
              with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: 'django-libraryapp'
                heroku_email: ${{EMAIL_DEPLOY}}
            - name: Success message
              run: echo Successfully Deploy.!