name: Check lint and test django application

on:
  push:
    branches:
      - 'feature/**'

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: set up python 3.7
              uses: actions/setup-python@v2
              with:
                python-version: 3.7
            - name: Lint with flake8
              run: |
                python -m pip install --upgrade pip
                pip install flake8 black
                # -----------------------
                # stop the build if there are Python syntax errors or undefined names
                # -----------------------
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # -----------------------
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                # -----------------------
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
                # -----------------------
                # checks with black
                # -----------------------
                black --diff .
            - name: Runing tests
              run: |
                pip install -r requirements.txt
                python3 manage.py migrate
                python3 manage.py test
            - name: Success message
              run: echo Successfully Testing.!